import React, { Component } from 'react';
import KnowerWrapp from '../include/knower-wrapp';
import Footer from '../include/footer';
import Header from '../include/header';
import { NavLink } from 'react-router-dom';
import LinkerWrapp from '../include/linker-wrapp';
import JudgerWrapp from '../include/judger-wrapp';
import CallusWrapp from '../include/callus-wrapp';
import ImpoerWrapp from '../include/impoer-wrapp';

class Privacy extends Component {
  
  render() {

    return (
<div>

<Header />
	<LinkerWrapp />
    <section className="banner-wrapp inner-wrapp">
	<div className="margin">
    	<div className="inner-row1">
        	<ul className="inner-bar1">
            	<li><NavLink to={Config.BASE_URL}>Home</NavLink></li>
                <li>/</li>
                <li>Privacy Policy</li>
            </ul>
        </div>
    </div>
</section>

<section className="inner-head">
	<div className="margin">
    	<h2>Privacy Policy</h2>
    </div>
</section>

<section className="conten-wrapp">
	<div className="margin">
    	
		<div className="conten-row1 policy-wrapp">
			
			<p>Dawabag cares about you and knows that you care how your information is used and or may be used or shared. By visiting https://Dawabag.in/ , you are accepting and consenting to the practices described in this Privacy Policy. This policy is issued by Axelia Solutions Private Limited.</p>

			<p>This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.</p>

			<p>This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of www.Dawabag.in website and its mobile applications.</p> 
            
            <p>By using this Website, you agree to the terms and conditions of this Privacy Policy. If you do not agree with the Terms and Conditions of this Privacy Policy, please do not proceed further to use this Website. This Privacy Policy is subject to change at any time without notice. To make sure you are aware of any changes, please review this policy periodically. This Privacy Policy is incorporated into and subject to the Terms of Use.</p>
            <p>For the purpose of this Privacy Policy, wherever the context so requires "You" or "User" shall mean any natural or legal person who has agreed to become a buyer on the Website by providing Personal Information (defined below) while registering on the Website as a registered User using the computer systems..</p> 
            
            <h2>1. What Personal Information About You Does Dawabag collect?</h2>  
            <p>The information we learn from customers helps us personalise and continuously improve your experience at Dawabag. Your information so collected may be used to assist retailers in handling orders, delivery through your agent and ancillary services, process payments, communicate with you about orders, products, services and promotional offers, update our records and generally maintain your accounts with us. We also use this information to improve our platform, prevent or detect fraud or abuses of our website and enable third parties to carry out technical, logistical or other functions on our behalf.</p>  
            <p>Permission You give Us: We use third party SDKs in our app. Majority of them are different payment options by which You can make a payment for an order. In order to enhance Your personal and overall experience some of the tools are used therein.</p>       
            <p>Third Party tools: We use third party SDKs in our app. Majority of them are different payment options by which You can make a payment for an order. In order to enhance Your personal and overall experience some of the tools are used therein.</p>
            <p>Information You Give Us: We receive and store any information you enter on our website or give us in any other way. Click here (Search, order Medicine, order OTC products, book a doctor consultation, schedule diagnostic test, etc., Prescription for medicine order or diagnostic test, Patient details, Diseases for doctor consultation, Address, Phone Number, Email id) to see examples of what we collect. You can choose not to provide certain information but then you might not be able to take advantage of many of our features. We use the information that you provide for such purposes as responding to your requests, customising your orders, improving our platform, communicating with you.</p>
            
            <h2>2. Does Dawabag.in share the Information it receives</h2>
            <p>Information about You and the other users of Dawabag forms an integral part of our business. Dawabag may only share the customer information as described below after ensuring that such third party has implemented measures to assure data protection measures and that are either subject to this Privacy Policy or follow practices at least as protective as those described in this Privacy Policy. Dawabag has arrangements with third parties (as mentioned below) such as service providers, retailers, payment gateways, logistics partners who may have access to the SPDI but shall not disclose such SPDI further to any other individual / entity.</p>
            <p>Information about You and the other users of Dawabag forms an integral part of our business. Dawabag may only share the customer information as described below after ensuring that such third party has implemented measures to assure data protection measures and that are either subject to this Privacy Policy or follow practices at least as protective as those described in this Privacy Policy. Dawabag has arrangements with third parties (as mentioned below) such as service providers, retailers, payment gateways, logistics partners who may have access to the SPDI but shall not disclose such SPDI further to any other individual / entity.</p>
            
            <h2>3. Does Dawabag.in share the Information it receives</h2>
            <p>Information about You and the other users of Dawabag forms an integral part of our business. Dawabag may only share the customer information as described below after ensuring that such third party has implemented measures to assure data protection measures and that are either subject to this Privacy Policy or follow practices at least as protective as those described in this Privacy Policy. Dawabag has arrangements with third parties (as mentioned below) such as service providers, retailers, payment gateways, logistics partners who may have access to the SPDI but shall not disclose such SPDI further to any other individual / entity.</p>
            
            <h2>4. Does Dawabag.in share the Information it receives</h2>
            <p>Information about You and the other users of Dawabag forms an integral part of our business. Dawabag may only share the customer information as described below after ensuring that such third party has implemented measures to assure data protection measures and that are either subject to this Privacy Policy or follow practices at least as protective as those described in this Privacy Policy. Dawabag has arrangements with third parties (as mentioned below) such as service providers, retailers, payment gateways, logistics partners who may have access to the SPDI but shall not disclose such SPDI further to any other individual / entity.</p>
            <p>Information about You and the other users of Dawabag forms an integral part of our business. Dawabag may only share the customer information as described below after ensuring that such third party has implemented measures to assure data protection measures and that are either subject to this Privacy Policy or follow practices at least as protective as those described in this Privacy Policy. Dawabag has arrangements with third parties (as mentioned below) such as service providers, retailers, payment gateways, logistics partners who may have access to the SPDI but shall not disclose such SPDI further to any other individual / entity.</p>
            <p>Information about You and the other users of Dawabag forms an integral part of our business. Dawabag may only share the customer information as described below after ensuring that such third party has implemented measures to assure data protection measures and that are either subject to this Privacy Policy or follow practices at least as protective as those described in this Privacy Policy. Dawabag has arrangements with third parties (as mentioned below) such as service providers, retailers, payment gateways, logistics partners who may have access to the SPDI but shall not disclose such SPDI further to any other individual / entity.</p>
            
            <h2>5. Does Dawabag.in share the Information it receives</h2>
            <p>Information about You and the other users of Dawabag forms an integral part of our business. Dawabag may only share the customer information as described below after ensuring that such third party has implemented measures to assure data protection measures and that are either subject to this Privacy Policy or follow practices at least as protective as those described in this Privacy Policy. Dawabag has arrangements with third parties (as mentioned below) such as service providers, retailers, payment gateways, logistics partners who may have access to the SPDI but shall not disclose such SPDI further to any other individual / entity.</p>
            
            <h2>6. Does Dawabag.in share the Information it receives</h2>
            <p>Information about You and the other users of Dawabag forms an integral part of our business. Dawabag may only share the customer information as described below after ensuring that such third party has implemented measures to assure data protection measures and that are either subject to this Privacy Policy or follow practices at least as protective as those described in this Privacy Policy. Dawabag has arrangements with third parties (as mentioned below) such as service providers, retailers, payment gateways, logistics partners who may have access to the SPDI but shall not disclose such SPDI further to any other individual / entity.</p>
                           
		</div>
        
	</div>
</section>

<ImpoerWrapp />
<JudgerWrapp />
<CallusWrapp />
<KnowerWrapp />
<Footer />
</div>
    );
  }
}

export default Privacy;
